//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STore_FRONt.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class F_StoreEntities3 : DbContext
    {
        public F_StoreEntities3()
            : base("name=F_StoreEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product> Products { get; set; }

        public System.Data.Entity.DbSet<STore_FRONt.Models.Order> Orders { get; set; }

        public System.Data.Entity.DbSet<STore_FRONt.Models.Contact_Information> Contact_Information { get; set; }

        public System.Data.Entity.DbSet<STore_FRONt.Models.Contact_Infos> Contact_Infos { get; set; }
    }
}
