//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STore_FRONt.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contact_Infos
    {
        public int ID { get; set; }

        [MinLength(1)]
        [StringLength(10, ErrorMessage = "Max Length is 10 Charcters")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use letters only please")]
        [Required(ErrorMessage ="Pleace Insert First Name")]
        public string First_Name { get; set; }

        [MinLength(1)]
        [StringLength(10, ErrorMessage = "Max Length is 10 Charcters")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use letters only please")]

        [Required(ErrorMessage = "Pleace Insert Last Name")]
        public string Last_Name { get; set; }

        [MinLength(10 , ErrorMessage ="Must Enter at least 10 Numbers")]
        [StringLength(10, ErrorMessage = "Must Enter at least 10 Numbers")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Phone Number format is not valid.")]
        [Required(ErrorMessage = "Pleace Insert Phone Number")]
        public string Phone_Number { get; set; }


        [MinLength(1)]
        [StringLength(15, ErrorMessage = "Max Length is 15 Charcters")]


        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use letters only please")]

        [Required(ErrorMessage = "Pleace Insert Address")]
        public string Adress { get; set; }
    }
}
